---
- name: "Check that filebeat's deb is exists"
  stat:
    path: "{{ pkg_tmp_src }}/filebeat-{{ filebeat_version }}-amd64.deb"
  register: stat_result
  delegate_to: localhost
- name: "Download filebeat's deb"
  get_url:
    url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ filebeat_version }}-amd64.deb"
    dest: "{{ pkg_tmp_src }}/filebeat-{{ filebeat_version }}-amd64.deb"
    validate_certs: false
  delegate_to: localhost
  register: download_filebeat
  until: download_filebeat is succeeded
  when: 
  - not stat_result.stat.exists
  - filebeat_install_type == 'remote'
- name: Copy filebeat to manage host
  copy:
    src: "{{ pkg_tmp_src }}/filebeat-{{ filebeat_version }}-amd64.deb"
    mode: 0755
    dest: "/tmp/filebeat-{{ filebeat_version }}-amd64.deb"
